inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3

Lint/HandleExceptions:
  Exclude:
    - 'spec/**/*'
    - 'lib/zizia/spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/hyrax/basic_metadata.rb'
    - 'lib/zizia/hyrax_record_importer.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/zizia/spec/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/zizia/hyrax_basic_metadata_mapper.rb
    - lib/zizia/hyrax_record_importer.rb

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/support/hyrax/basic_metadata.rb'
    - 'lib/zizia/hyrax_basic_metadata_mapper.rb'
    - lib/zizia/hyrax_record_importer.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/zizia/hyrax_record_importer.rb

Naming/AccessorMethodName:
  Exclude:
    - lib/zizia/hyrax_record_importer.rb

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/*_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/zizia/hyrax_basic_metadata_mapper_spec.rb'
    - 'spec/integration/import_hyrax_csv.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/zizia/hyrax_basic_metadata_mapper_spec.rb'
    - 'spec/integration/import_hyrax_csv.rb'

Style/StructInheritance:
  Enabled: false
