---
# Metadata usage hints
# attribute: usage

arkivo_checksum:        "-- system field - not directly editable --"
based_near: " A location that something is based near, for some broadly human notion of near."
contributor:            "Identifies contributors to the material; can be used very broadly if exact contributions aren't known"
creator:                "Identifies the primary Creator(s) of the material"
date_created:           "The date the material was created"
date_modified:          "-- system field - not directly editable --"
date_uploaded:          "-- system field - not directly editable --"
depositor:              "-- system field - not directly editable --"
description:            "Free-text, summary description of the content, such as an abstract. Provides additional search terms in natural language; provides important summary information for non-textual resources such as images, audio, and video"
has_model:              "-- system field - not directly editable --"
head:                   "-- system field - not directly editable --"
identifier: "An unambiguous reference to the resource within a given context."
keywords:               "Uncontrolled keywords describing the material, often provided by content creators"
language:       "The language of the source content being described: applies to textual or spoken word (linguistic) content"
license: "A legal document giving official permission to do something with the resource."
on_behalf_of:           "-- system field - not directly editable --"
owner:                  "-- system field - not directly editable --"
proxy_depositor:        "-- system field - not directly editable --"
publisher:              "The name of the entity formally publishing the work"
related_url: "The resource O may provide additional information about S. It may be possible to retrieve representations of O from the Web, but this is not required. When such representations may be retrieved, no constraints are placed on the format of those representations."
resource_type: "The nature or genre of the resource."
rights_statement:       "Standardized rights statement from rightsstatements.org that can be used to communicate the copyright and re-use status of digital objects to the end users  [DESCRIPTIVE/USER FACING]"
source: "A related resource from which the described resource is derived."
state:                  "-- system field - not directly editable --"
tail:                    "-- system field - not directly editable --"
title:                  "The name of the resource being described. The title may either be transcribed from the resource itself, or it may need to be created."
